import type { Metadata } from 'next';
import { Gaegu } from 'next/font/google';
import './globals.css';

const gaeguLight = Gaegu({
  subsets: ['latin'],
  variable: '--font-gaegu-light',
  weight: '300',
});
const gaeguRegular = Gaegu({
  subsets: ['latin'],
  variable: '--font-gaegu-regular',
  weight: '400',
});
const gaeguBold = Gaegu({
  subsets: ['latin'],
  variable: '--font-gaegu-bold',
  weight: '700',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${gaeguLight.variable} ${gaeguBold.variable} ${gaeguRegular.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
